name: compile_mac

on: [push]

env:
  BUILD_TYPE: Release
  WXVERSION: 3.1.4

jobs:
  compile_Ninja:
    runs-on: macos-latest

    steps:
    - name: Checkout_git
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 15
    - name: install_packages
      run: |
           export PATH=$PATH:/usr/local/opt/gettext/bin
           export HOMEBREW_NO_AUTO_UPDATE=1
           set -e
           brew upgrade cmake
           brew install gettext ninja pandoc wget
           brew link cmake
           set +e
    - name: download_wxWidgets
      run: |
           wget https://github.com/wxWidgets/wxWidgets/releases/download/v${{env.WXVERSION}}/wxWidgets-${{env.WXVERSION}}.zip
           mkdir wxWidgets_src
           cd wxWidgets_src
           unzip ../wxWidgets-${{env.WXVERSION}}.zip
           cd ..
    - name: compile_wxWidgets
      run: |
           mkdir wxWidgets_build
           cd wxWidgets_build
           cmake ../wxWidgets_src -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
           make
           sudo make install
           cd ..
    - name: configure
      run: |
           mkdir ../build-wxm
           cmake -S . -B ../build-wxm -G Ninja -DCMAKE_INSTALL_PREFIX=. -DCMAKE_UNITY_BUILD_BATCH_SIZE=8 -DWXM_UNIT_TESTS=YES -DCMAKE_UNITY_BUILD=YES -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"

    - name: plist_check
      run: |
           ls -l ../build-wxm/src/Info.plist
    - name: compile
      run: |
           cmake --build ../build-wxm
    - name: install
      run: |
           cmake --install ../build-wxm

  compile_Make:
    runs-on: macos-latest

    steps:
    - name: Checkout_git
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 15
    - name: install_packages
      run: |
           export PATH=$PATH:/usr/local/opt/gettext/bin
           export HOMEBREW_NO_AUTO_UPDATE=1
           set -e
           brew upgrade cmake
           brew install gettext libomp wxwidgets
           brew link cmake
           set +e
    - name: configure
      run: |
           mkdir ../build-wxm
           cmake -S . -B ../build-wxm -DCMAKE_INSTALL_PREFIX=.
    - name: plist_check
      run: |
           ls -l ../build-wxm/src/Info.plist
    - name: compile
      run: |
           cmake --build ../build-wxm
    - name: install
      run: |
           cmake --install ../build-wxm
