name: compile_mac

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  compile_Ninja:
    runs-on: macos-latest

    steps:
    - name: Checkout_git
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 15
    - name: install_packages
      run: |
           export PATH=$PATH:/usr/local/opt/gettext/bin
           export HOMEBREW_NO_AUTO_UPDATE=1
           set -e
           brew upgrade cmake
           brew install gettext libomp ninja pandoc wxwidgets
           brew link cmake
           set +e
    - name: configure
      run: |
           mkdir ../build-wxm
           cmake -S . -B ../build-wxm -G Ninja -DCMAKE_INSTALL_PREFIX=. -DCMAKE_UNITY_BUILD_BATCH_SIZE=8 -DWXM_UNIT_TESTS=YES -DCMAKE_UNITY_BUILD=YES
    - name: plist_check
      run: |
           ls -l ../build-wxm/data/Info.plist
    - name: compile
      run: |
           cmake --build ../build-wxm
    - name: install
      run: |
           cmake --install ../build-wxm

  compile_Make:
    runs-on: macos-latest

    steps:
    - name: Checkout_git
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 15
    - name: install_packages
      run: |
           export PATH=$PATH:/usr/local/opt/gettext/bin
           export HOMEBREW_NO_AUTO_UPDATE=1
           set -e
           brew upgrade cmake
           brew install gettext libomp wxwidgets
           brew link cmake
           set +e
    - name: configure
      run: |
           mkdir ../build-wxm
           cmake -S . -B ../build-wxm -DCMAKE_INSTALL_PREFIX=.
    - name: plist_check
      run: |
           ls -l ../build-wxm/data/Info.plist
    - name: compile
      run: |
           cmake --build ../build-wxm
    - name: install
      run: |
           cmake --install ../build-wxm
